update_subscription_status_scheduler:
  cron: '0 0 * * *'
  class: 'UpdateSubscriptionStatusScheduler'
  queue: 'default'

# subscription_renewal_job:
#   cron: '0 0 * * *'   
#   class: 'SubscriptionRenewalJob'
#   queue: 'default'
  
reset_blog_view_sheduler:
  cron: '0 0 * * *'
  class: 'ResetBlogViewScheduler'
  queue: 'default'

subscription_expiration_scheduler:
  cron: '0 0 * * *'
  class: 'SubscriptionExpirationScheduler'
  queue: 'default'

expiration_notification_scheduler:
  cron: '0 0 * * *'
  class: 'ExpirationNotificationScheduler'
  queue: 'default'

