auto_renewal_worker:
  cron: '0 0 * * *'
  class: 'AutoRenewalWorker'
  queue: 'default'

expiration_notification_worker:
  cron: '0 0 * * *'   
  class: 'ExpirationNotificationWorker'
  queue: 'default'
  
reset_user_blog_views_worker:
  cron: '0 0 * * *'
  class: 'ResetBlogViewWorker'
  queue: 'default'

reset_blog_views_count_worker:
  cron: '0 0 * * *'
  class: 'ResetBlogViewsCountWorker'
  queue: 'default'

update_subscription_status_worker:
  cron: '0 0 * * *'
  class: 'UpdateSubscriptionStatusWorker'
  queue: 'default'

